/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StudentImport } from './routes/student'
import { Route as ProfileImport } from './routes/profile'
import { Route as PostsImport } from './routes/posts'
import { Route as NewsImport } from './routes/news'
import { Route as AllusersImport } from './routes/all_users'
import { Route as AdminImport } from './routes/admin'
import { Route as AbsencesImport } from './routes/absences'
import { Route as PostsIndexImport } from './routes/posts.index'
import { Route as NewsIndexImport } from './routes/news/index'
import { Route as AbsencesIndexImport } from './routes/absences/index'
import { Route as PostsPostIdImport } from './routes/posts.$postId'
import { Route as NewsCreateImport } from './routes/news/create'
import { Route as NewsNewsidImport } from './routes/news/$news_id'
import { Route as HrclassStudentsImport } from './routes/hr_class/students'
import { Route as AdminSchoolEventImport } from './routes/admin/schoolEvent'
import { Route as AdminClassImport } from './routes/admin/class'
import { Route as AbsencesAbsenceidImport } from './routes/absences/$absence_id'
import { Route as HrclassStudentsIndexImport } from './routes/hr_class/students/index'
import { Route as HrclassStudentsStudentidImport } from './routes/hr_class/students/$student_id'

// Create/Update Routes

const StudentRoute = StudentImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRoute,
} as any)

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const PostsRoute = PostsImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRoute,
} as any)

const NewsRoute = NewsImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRoute,
} as any)

const AllusersRoute = AllusersImport.update({
  id: '/all_users',
  path: '/all_users',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const AbsencesRoute = AbsencesImport.update({
  id: '/absences',
  path: '/absences',
  getParentRoute: () => rootRoute,
} as any)

const PostsIndexRoute = PostsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRoute,
} as any)

const NewsIndexRoute = NewsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewsRoute,
} as any)

const AbsencesIndexRoute = AbsencesIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AbsencesRoute,
} as any)

const PostsPostIdRoute = PostsPostIdImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsRoute,
} as any)

const NewsCreateRoute = NewsCreateImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => NewsRoute,
} as any)

const NewsNewsidRoute = NewsNewsidImport.update({
  id: '/$news_id',
  path: '/$news_id',
  getParentRoute: () => NewsRoute,
} as any)

const HrclassStudentsRoute = HrclassStudentsImport.update({
  id: '/hr_class/students',
  path: '/hr_class/students',
  getParentRoute: () => rootRoute,
} as any)

const AdminSchoolEventRoute = AdminSchoolEventImport.update({
  id: '/schoolEvent',
  path: '/schoolEvent',
  getParentRoute: () => AdminRoute,
} as any)

const AdminClassRoute = AdminClassImport.update({
  id: '/class',
  path: '/class',
  getParentRoute: () => AdminRoute,
} as any)

const AbsencesAbsenceidRoute = AbsencesAbsenceidImport.update({
  id: '/$absence_id',
  path: '/$absence_id',
  getParentRoute: () => AbsencesRoute,
} as any)

const HrclassStudentsIndexRoute = HrclassStudentsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HrclassStudentsRoute,
} as any)

const HrclassStudentsStudentidRoute = HrclassStudentsStudentidImport.update({
  id: '/$student_id',
  path: '/$student_id',
  getParentRoute: () => HrclassStudentsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/absences': {
      id: '/absences'
      path: '/absences'
      fullPath: '/absences'
      preLoaderRoute: typeof AbsencesImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/all_users': {
      id: '/all_users'
      path: '/all_users'
      fullPath: '/all_users'
      preLoaderRoute: typeof AllusersImport
      parentRoute: typeof rootRoute
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsImport
      parentRoute: typeof rootRoute
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentImport
      parentRoute: typeof rootRoute
    }
    '/absences/$absence_id': {
      id: '/absences/$absence_id'
      path: '/$absence_id'
      fullPath: '/absences/$absence_id'
      preLoaderRoute: typeof AbsencesAbsenceidImport
      parentRoute: typeof AbsencesImport
    }
    '/admin/class': {
      id: '/admin/class'
      path: '/class'
      fullPath: '/admin/class'
      preLoaderRoute: typeof AdminClassImport
      parentRoute: typeof AdminImport
    }
    '/admin/schoolEvent': {
      id: '/admin/schoolEvent'
      path: '/schoolEvent'
      fullPath: '/admin/schoolEvent'
      preLoaderRoute: typeof AdminSchoolEventImport
      parentRoute: typeof AdminImport
    }
    '/hr_class/students': {
      id: '/hr_class/students'
      path: '/hr_class/students'
      fullPath: '/hr_class/students'
      preLoaderRoute: typeof HrclassStudentsImport
      parentRoute: typeof rootRoute
    }
    '/news/$news_id': {
      id: '/news/$news_id'
      path: '/$news_id'
      fullPath: '/news/$news_id'
      preLoaderRoute: typeof NewsNewsidImport
      parentRoute: typeof NewsImport
    }
    '/news/create': {
      id: '/news/create'
      path: '/create'
      fullPath: '/news/create'
      preLoaderRoute: typeof NewsCreateImport
      parentRoute: typeof NewsImport
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdImport
      parentRoute: typeof PostsImport
    }
    '/absences/': {
      id: '/absences/'
      path: '/'
      fullPath: '/absences/'
      preLoaderRoute: typeof AbsencesIndexImport
      parentRoute: typeof AbsencesImport
    }
    '/news/': {
      id: '/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexImport
      parentRoute: typeof NewsImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexImport
      parentRoute: typeof PostsImport
    }
    '/hr_class/students/$student_id': {
      id: '/hr_class/students/$student_id'
      path: '/$student_id'
      fullPath: '/hr_class/students/$student_id'
      preLoaderRoute: typeof HrclassStudentsStudentidImport
      parentRoute: typeof HrclassStudentsImport
    }
    '/hr_class/students/': {
      id: '/hr_class/students/'
      path: '/'
      fullPath: '/hr_class/students/'
      preLoaderRoute: typeof HrclassStudentsIndexImport
      parentRoute: typeof HrclassStudentsImport
    }
  }
}

// Create and export the route tree

interface AbsencesRouteChildren {
  AbsencesAbsenceidRoute: typeof AbsencesAbsenceidRoute
  AbsencesIndexRoute: typeof AbsencesIndexRoute
}

const AbsencesRouteChildren: AbsencesRouteChildren = {
  AbsencesAbsenceidRoute: AbsencesAbsenceidRoute,
  AbsencesIndexRoute: AbsencesIndexRoute,
}

const AbsencesRouteWithChildren = AbsencesRoute._addFileChildren(
  AbsencesRouteChildren,
)

interface AdminRouteChildren {
  AdminClassRoute: typeof AdminClassRoute
  AdminSchoolEventRoute: typeof AdminSchoolEventRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClassRoute: AdminClassRoute,
  AdminSchoolEventRoute: AdminSchoolEventRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface NewsRouteChildren {
  NewsNewsidRoute: typeof NewsNewsidRoute
  NewsCreateRoute: typeof NewsCreateRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsNewsidRoute: NewsNewsidRoute,
  NewsCreateRoute: NewsCreateRoute,
  NewsIndexRoute: NewsIndexRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface PostsRouteChildren {
  PostsPostIdRoute: typeof PostsPostIdRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsPostIdRoute: PostsPostIdRoute,
  PostsIndexRoute: PostsIndexRoute,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

interface HrclassStudentsRouteChildren {
  HrclassStudentsStudentidRoute: typeof HrclassStudentsStudentidRoute
  HrclassStudentsIndexRoute: typeof HrclassStudentsIndexRoute
}

const HrclassStudentsRouteChildren: HrclassStudentsRouteChildren = {
  HrclassStudentsStudentidRoute: HrclassStudentsStudentidRoute,
  HrclassStudentsIndexRoute: HrclassStudentsIndexRoute,
}

const HrclassStudentsRouteWithChildren = HrclassStudentsRoute._addFileChildren(
  HrclassStudentsRouteChildren,
)

export interface FileRoutesByFullPath {
  '/absences': typeof AbsencesRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/all_users': typeof AllusersRoute
  '/news': typeof NewsRouteWithChildren
  '/posts': typeof PostsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/student': typeof StudentRoute
  '/absences/$absence_id': typeof AbsencesAbsenceidRoute
  '/admin/class': typeof AdminClassRoute
  '/admin/schoolEvent': typeof AdminSchoolEventRoute
  '/hr_class/students': typeof HrclassStudentsRouteWithChildren
  '/news/$news_id': typeof NewsNewsidRoute
  '/news/create': typeof NewsCreateRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/absences/': typeof AbsencesIndexRoute
  '/news/': typeof NewsIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/hr_class/students/$student_id': typeof HrclassStudentsStudentidRoute
  '/hr_class/students/': typeof HrclassStudentsIndexRoute
}

export interface FileRoutesByTo {
  '/admin': typeof AdminRouteWithChildren
  '/all_users': typeof AllusersRoute
  '/profile': typeof ProfileRoute
  '/student': typeof StudentRoute
  '/absences/$absence_id': typeof AbsencesAbsenceidRoute
  '/admin/class': typeof AdminClassRoute
  '/admin/schoolEvent': typeof AdminSchoolEventRoute
  '/news/$news_id': typeof NewsNewsidRoute
  '/news/create': typeof NewsCreateRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/absences': typeof AbsencesIndexRoute
  '/news': typeof NewsIndexRoute
  '/posts': typeof PostsIndexRoute
  '/hr_class/students/$student_id': typeof HrclassStudentsStudentidRoute
  '/hr_class/students': typeof HrclassStudentsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/absences': typeof AbsencesRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/all_users': typeof AllusersRoute
  '/news': typeof NewsRouteWithChildren
  '/posts': typeof PostsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/student': typeof StudentRoute
  '/absences/$absence_id': typeof AbsencesAbsenceidRoute
  '/admin/class': typeof AdminClassRoute
  '/admin/schoolEvent': typeof AdminSchoolEventRoute
  '/hr_class/students': typeof HrclassStudentsRouteWithChildren
  '/news/$news_id': typeof NewsNewsidRoute
  '/news/create': typeof NewsCreateRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/absences/': typeof AbsencesIndexRoute
  '/news/': typeof NewsIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/hr_class/students/$student_id': typeof HrclassStudentsStudentidRoute
  '/hr_class/students/': typeof HrclassStudentsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/absences'
    | '/admin'
    | '/all_users'
    | '/news'
    | '/posts'
    | '/profile'
    | '/student'
    | '/absences/$absence_id'
    | '/admin/class'
    | '/admin/schoolEvent'
    | '/hr_class/students'
    | '/news/$news_id'
    | '/news/create'
    | '/posts/$postId'
    | '/absences/'
    | '/news/'
    | '/posts/'
    | '/hr_class/students/$student_id'
    | '/hr_class/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/all_users'
    | '/profile'
    | '/student'
    | '/absences/$absence_id'
    | '/admin/class'
    | '/admin/schoolEvent'
    | '/news/$news_id'
    | '/news/create'
    | '/posts/$postId'
    | '/absences'
    | '/news'
    | '/posts'
    | '/hr_class/students/$student_id'
    | '/hr_class/students'
  id:
    | '__root__'
    | '/absences'
    | '/admin'
    | '/all_users'
    | '/news'
    | '/posts'
    | '/profile'
    | '/student'
    | '/absences/$absence_id'
    | '/admin/class'
    | '/admin/schoolEvent'
    | '/hr_class/students'
    | '/news/$news_id'
    | '/news/create'
    | '/posts/$postId'
    | '/absences/'
    | '/news/'
    | '/posts/'
    | '/hr_class/students/$student_id'
    | '/hr_class/students/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AbsencesRoute: typeof AbsencesRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AllusersRoute: typeof AllusersRoute
  NewsRoute: typeof NewsRouteWithChildren
  PostsRoute: typeof PostsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  StudentRoute: typeof StudentRoute
  HrclassStudentsRoute: typeof HrclassStudentsRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AbsencesRoute: AbsencesRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AllusersRoute: AllusersRoute,
  NewsRoute: NewsRouteWithChildren,
  PostsRoute: PostsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  StudentRoute: StudentRoute,
  HrclassStudentsRoute: HrclassStudentsRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/absences",
        "/admin",
        "/all_users",
        "/news",
        "/posts",
        "/profile",
        "/student",
        "/hr_class/students"
      ]
    },
    "/absences": {
      "filePath": "absences.tsx",
      "children": [
        "/absences/$absence_id",
        "/absences/"
      ]
    },
    "/admin": {
      "filePath": "admin.tsx",
      "children": [
        "/admin/class",
        "/admin/schoolEvent"
      ]
    },
    "/all_users": {
      "filePath": "all_users.tsx"
    },
    "/news": {
      "filePath": "news.tsx",
      "children": [
        "/news/$news_id",
        "/news/create",
        "/news/"
      ]
    },
    "/posts": {
      "filePath": "posts.tsx",
      "children": [
        "/posts/$postId",
        "/posts/"
      ]
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/student": {
      "filePath": "student.tsx"
    },
    "/absences/$absence_id": {
      "filePath": "absences/$absence_id.tsx",
      "parent": "/absences"
    },
    "/admin/class": {
      "filePath": "admin/class.tsx",
      "parent": "/admin"
    },
    "/admin/schoolEvent": {
      "filePath": "admin/schoolEvent.tsx",
      "parent": "/admin"
    },
    "/hr_class/students": {
      "filePath": "hr_class/students.tsx",
      "children": [
        "/hr_class/students/$student_id",
        "/hr_class/students/"
      ]
    },
    "/news/$news_id": {
      "filePath": "news/$news_id.tsx",
      "parent": "/news"
    },
    "/news/create": {
      "filePath": "news/create.tsx",
      "parent": "/news"
    },
    "/posts/$postId": {
      "filePath": "posts.$postId.tsx",
      "parent": "/posts"
    },
    "/absences/": {
      "filePath": "absences/index.tsx",
      "parent": "/absences"
    },
    "/news/": {
      "filePath": "news/index.tsx",
      "parent": "/news"
    },
    "/posts/": {
      "filePath": "posts.index.tsx",
      "parent": "/posts"
    },
    "/hr_class/students/$student_id": {
      "filePath": "hr_class/students/$student_id.tsx",
      "parent": "/hr_class/students"
    },
    "/hr_class/students/": {
      "filePath": "hr_class/students/index.tsx",
      "parent": "/hr_class/students"
    }
  }
}
ROUTE_MANIFEST_END */
